perf(input): implementa ChangeDetectionStrategy OnPush
po-ui/po-angular pull request #1012
Opened 2021-09-17 19:16 UTC by jcorrea97

**Input**

**DTHFUI-5279**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
O component Input utiliza o ChangeDetectionStragy.Default

**Qual o novo comportamento?**
O component Input utiliza o ChangeDetectionStrategy.OnPush

**Simulação**
Testar Input e DynamicForm. Pode utilizar o labs do portal

2021-09-20 14:35 UTC, jribeiroo approved these changes

2021-09-20 18:04 UTC, rafaellmarques approved these changes

2021-09-20 19:27 UTC, jhonyeduardo requested changes
2 cenários com problemas:

1. Ao iniciar campo com valor e ter o atributo "p-clean=true", não estava apresentando o ícone de "limpar"

![image](https://user-images.githubusercontent.com/6907801/134062340-ebae987b-f040-476f-85cc-e7d95f779c60.png)



----

2. Ao desabilitar um campo via reactive form, o mesmo não é refletido em tela:

Exemplos para simular o problema:
```
<po-input name="input" [(ngModel)]="input" p-label="INPUT" [p-clean]="true"></po-input>
<hr>

model: {{ input }}

<hr>

<po-button (p-click)="onclick()" p-label="ALTERAR INPUT NGMODEL"></po-button>

<hr>

<form [formGroup]="group">
  <po-input formControlName="inputreativo" p-label="INPUT REATIVO" [p-clean]="true"></po-input>
</form>

model: {{ group.get('inputreativo').value }}

<hr>

<po-button (p-click)="disableReactive()" p-label="DISABLE REACTIVE INPUT"></po-button>



// ts

 input;
 group;

 constructor(formBuild: FormBuilder) {
    this.group = formBuild.group({
      inputreativo: ['']
    });
 }

 onclick() {
    this.input = 'VALOR';
 }

 disableReactive() {
    if (this.group.get('inputreativo').disabled) {
      this.group.get('inputreativo').enable();
    } else {
      this.group.get('inputreativo').disable();
    }
 }
```



**Sugestão de Solução:**
Após uns testes, para resolver o problema, devemos invocar o método `changeDetectorRef.markForCheck` nos pontos onde queremos que seja feito a detecção de mudança (quando precisamos checar algo no template mas não é alterado um @Input ou @Output), como por exemplo: writeValue e setDisableState

2021-09-21 20:50 UTC, jribeiroo approved these changes

2021-09-21 20:50 UTC, rafaellmarques approved these changes

2021-09-21 21:27 UTC, jhonyeduardo approved these changes

2021-09-21 21:27 UTC, merged