feat(modal-footer): cria componente `modal-footer`
po-ui/po-angular pull request #1087
Opened 2021-11-04 21:23 UTC by jribeiroo

MODAL-FOOTER

DTHFUI-4864
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
Rodapé do modal possui um alinhamento padrão a direita, para os botões de ações.

**Qual o novo comportamento?**
Da liberdade ao desenvolvedor personalizar o alinhamento e a quantidade de botões de ações. 

**Simulação**
`app.component.html`
```
<div class="po-p-2">
  <po-modal #modal p-title="PO Modal">
    We are TOTVERS!!!
    <po-modal-footer [p-disabled-align]="true">
      <po-button p-label="Tertiary Action"> </po-button>
      <po-button p-label="Secondary Action"> </po-button>
      <po-button p-label="Primary Action"> </po-button>
    </po-modal-footer>
  </po-modal>

  <po-button p-label="Open modal" (p-click)="modal.open()"> </po-button>
</div>
```
Ou rodar pelo portal.

2021-11-04 22:19 UTC, brunoromeiro requested changes

2021-11-04 22:19 UTC, brunoromeiro commented on projects/app/src/app/app.component.html
> +<sample-po-modal-fruits-salad></sample-po-modal-fruits-salad>
Remover este arquivo do commit.

2021-11-04 22:19 UTC, brunoromeiro commented on projects/app/src/app/app.module.ts
> +//import { PoModule } from '@po-ui/ng-components';
Remover também este arquivo do commit.

2021-11-04 22:19 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.ts
> + * O componente `po-modal-footer` pode ser utilizado para incluir os botões de ações no rodapé da [`PoModal`](/documentation/po-modal).
```suggestion
 * O componente `po-modal-footer` pode ser utilizado para incluir os botões de ações no rodapé da [`PoModal`], bem como para dar liberdade ao desenvolvedor de incluir outros itens necessários. (/documentation/po-modal).
```

2021-11-04 22:19 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.ts
> + *
> Como boa prática, deve-se observar a utilização de apenas um botão primário.

2021-11-04 22:19 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.ts
> +export class PoModalFooterComponent {
Olhando a issue senti falta do item: `Criar a propriedade p-align="start" | p-start-align | p-start-position`.

Este cara ficou para um outro momento?

2021-11-05 15:04 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-modal/po-modal-footer/po-modal-footer.component.ts
> + *
```suggestion
 * > Como boa prática, deve-se observar a utilização de apenas um botão primário.
```

2021-11-05 17:35 UTC, jribeiroo commented on projects/app/src/app/app.component.html
> +<sample-po-modal-fruits-salad></sample-po-modal-fruits-salad>
Realizado ajuste

2021-11-05 17:36 UTC, jribeiroo commented on projects/app/src/app/app.module.ts
> +//import { PoModule } from '@po-ui/ng-components';
Realizado ajuste

2021-11-05 18:24 UTC, brunoromeiro approved these changes

2021-11-05 18:25 UTC, gabrielibarbosa approved these changes

2021-11-05 18:32 UTC, merged