feat(page-dynamic-edit): adiciona atributo offset
po-ui/po-angular pull request #1182
Opened 2022-02-06 01:29 UTC by wsteixeira

Foi adicionado os atributos na interface PoDynamicField:
- offsetColumns
- offsetSmColumns
- offsetMdColumns
- offsetLgColumns
- offsetXlColumns

Fixes #1141

** Page Dynamic Edit **

** 1141 **
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O componente não tinha o atributo offset

**Qual o novo comportamento?**
Foi adicionado o atributo na interface PoDynamicField e como esta interface é estendida por outras, quatro componentes forambeneficiado:

- **Page Dynamic Edit**
- **Page Dynamic Detail**
- **Dynamic Form**
- **Dynamic View**

**Simulação**
A simulação pode ser feita no componente **Page Dynamic Edit**.

2022-05-06 19:36 UTC, gabrielibarbosa requested changes

2022-05-06 21:47 UTC, wsteixeira commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-field.interface.ts
> +   * > Esta propriedade é generica, aplica o valor em todos os tamanhos de telas.
Correção realizada.

2022-05-09 18:15 UTC, gabrielibarbosa approved these changes

2022-05-10 17:47 UTC, brunoromeiro approved these changes

2022-05-15 22:12 UTC, merged