fix(lookup): ajusta pesquisa de filtro avançado
po-ui/po-angular pull request #1220
Opened 2022-03-08 20:39 UTC by brunoromeiro

**LOOKUP**

**DTHFUI-5706**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O Registro não é encontrado após click em carregar mais resultados.

**Qual o novo comportamento?**
A paginação é resetada sempre que é fechado o modal de Advanced Search.

**Simulação**
Utilizar este [app](https://github.com/po-ui/po-angular/files/8209431/app.zip) ou utilizar no Portal com o exemplo `PO Lookup - Hero`, e seguir os seguintes passos abaixo:
1. Clique em Busca Avançada, e digite Peter Parker no Name;
2. Na tabela mostra os dados corretamente;
3. Limpar o filtro, e após clicar em Carregar mais resultados;
4. Repetindo a consulta do item 1.

2022-03-10 11:45 UTC, jcorrea97 submitted a review, later dismissed

2022-03-14 13:39 UTC, alinelariguet requested changes
Inclusão de testes que cubram a situação reportada.

2022-03-14 17:39 UTC, alinelariguet approved these changes

2022-03-14 18:11 UTC, jcorrea97 approved these changes

2022-03-14 18:18 UTC, merged