docs(page-dynamic-detail): ajusta propriedade p-auto-router com strict
po-ui/po-angular pull request #1263
Opened 2022-04-19 22:52 UTC by wsteixeira

A propriedade `strictTemplates` já vem configurado como `true`  na versão atual do Angular e desta forma o exemplo apresenta erro de compilação.

Fixes #1262

**Page Dynamic Edit**

**1262**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O exemplo está informando desta forma:
```
<po-page-dynamic-edit
  p-auto-router
  p-title="User edit"
  [p-actions]="actions"
  [p-breadcrumb]="breadcrumb"
  [p-fields]="fields"
  [p-service-api]="serviceApi"
>
</po-page-dynamic-edit>
```

**Qual o novo comportamento?**
Deve ser informado desta forma:
```
<po-page-dynamic-edit
  [p-auto-router]="true"
  p-title="User edit"
  [p-actions]="actions"
  [p-breadcrumb]="breadcrumb"
  [p-fields]="fields"
  [p-service-api]="serviceApi"
>
</po-page-dynamic-edit>
```
**Simulação**
Pode ser feita no portal.

2022-05-17 17:19 UTC, jhosefmarks approved these changes

2022-05-17 17:24 UTC, jhosefmarks requested changes
O componente alterado é o page-dynamic-edit.

2022-05-18 16:39 UTC, wsteixeira commented
> O componente alterado é o page-dynamic-edit.

Olá @jhosefmarks, titulo da PR e do commit renomeando!

2022-07-04 00:17 UTC, alinelariguet approved these changes

2022-07-04 11:32 UTC, brunoromeiro approved these changes

2022-07-04 13:37 UTC, merged