feat: implementa virtual scroll
po-ui/po-angular pull request #1270
Opened 2022-04-29 20:19 UTC by jribeiroo

**TABLE**

**DTHFUI-5921**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O componente table não possui cdk-virtual-scroll 

**Qual o novo comportamento?**
Componente table passa a ter cdk-virtual-scroll para melhor desempenho

**Simulação**
[app.zip](https://github.com/po-ui/po-angular/files/8594506/app.zip)

2022-04-29 21:46 UTC, brunoromeiro approved these changes

2022-04-29 21:57 UTC, jcorrea97 submitted a review, later dismissed

2022-04-30 03:57 UTC, alinelariguet requested changes
Correção necessária indicada no comentário abaixo.

2022-04-30 03:57 UTC, alinelariguet commented
No ambiente local quando eu acesso direto a url: https://po-ui.io/documentation, acesso o po-table e depois acesso a tab de exemplos, o componente se comporta como esperado. 
Ao acessar a url: https://po-ui.io/components/po-table diretamente o componente não renderiza todos os registros, somente os dez primeiros e quebrando o layout em pequenas resoluções conforme imagem abaixo. Em resoluções maiores o componente não quebra o layout porém continua renderizando somente os dez primeiros registros.
Pode ter relação com o fato do componente estar dentro de um po-tab (verificar).
![Captura de Tela 2022-04-30 às 12 38 09 AM](https://user-images.githubusercontent.com/42390783/166089433-d31e1f45-bfd6-4347-afef-d23796862def.png)

2022-05-24 12:47 UTC, brunoromeiro submitted a review, later dismissed

2022-05-24 23:33 UTC, gabrielibarbosa commented
No sample PO Table - Airfare se eu tiro as colunas, ele tá ficando assim

![image](https://user-images.githubusercontent.com/31509625/170148522-66785c3b-0648-4eb8-bd89-fa9615f01c4e.png)

2022-05-24 23:34 UTC, gabrielibarbosa commented
No caso, no sample, eu estou:
1° Adiciono 3 linhas
2º defino um Height pra table

Se eu tentar incluir mais linhas não funciona

![image](https://user-images.githubusercontent.com/31509625/170148588-9183938f-6c0a-4156-9e97-dd1dc5b99d05.png)

2022-05-24 23:36 UTC, gabrielibarbosa commented
Tentei gerar o build do portal e apresentou alguns erros. Vou deixar registrado pra caso esteja acontecendo com mais alguém.
`npm run build:portal`
![image](https://user-images.githubusercontent.com/31509625/170148696-58a4a2ba-6820-4661-81a1-0e5e4e3bd801.png)

2022-05-26 13:41 UTC, gabrielibarbosa approved these changes

2022-05-27 19:10 UTC, alinelariguet approved these changes

2022-05-27 19:10 UTC, merged