Universo/dthf UI 5935
po-ui/po-angular pull request #1273
Opened 2022-05-04 14:08 UTC by jcorrea97

**< COMPONENTE >**

**< NÚMERO DA ISSUE >**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**

**Qual o novo comportamento?**

**Simulação**

2022-05-05 13:54 UTC, brunoromeiro submitted a review, later dismissed

2022-05-06 19:52 UTC, jribeiroo approved these changes

2022-05-11 14:58 UTC, alinelariguet commented on projects/portal/src/app/app.component.html
> +  *ngIf="router.url !== '/theme-builder'"
```suggestion
  *ngIf="router.url !== '/construtor-de-temas'"
```

2022-05-11 14:59 UTC, alinelariguet commented on projects/portal/src/app/app.component.ts
> +      { label: 'Theme builder', link: '/theme-builder' },
```suggestion
      { label: 'Construtor de temas', link: '/construtor-de-temas' },
```

2022-05-11 14:59 UTC, alinelariguet commented on projects/portal/src/app/theme-builder/theme-builder.component.html
> +</div> -->
esse trecho pode ser removido?

2022-05-11 15:01 UTC, alinelariguet commented on projects/portal/src/app/theme-builder/theme-builder.component.html
> +        <label for="colorHoverD" class="po-mr-2 po-ml-1">Cor principal Hover: </label>
```suggestion
        <label for="colorHoverD" class="po-mr-2 po-ml-1">Cor da borda Hover: </label>
```

2022-05-11 15:01 UTC, alinelariguet commented on projects/portal/src/app/theme-builder/theme-builder.component.html
> +        <label for="colorD" class="po-mr-2 po-ml-1">Cor principal: </label>
```suggestion
        <label for="colorD" class="po-mr-2 po-ml-1">Cor da borda: </label>
```

2022-05-11 15:07 UTC, alinelariguet commented on projects/portal/src/app/theme-builder/theme-builder.component.html
> +        <label for="colorHoverL" class="po-mr-2 po-ml-1">Cor Hover: </label>
```suggestion
        <label for="colorHoverL" class="po-mr-2 po-ml-1">Cor do texto Hover: </label>
```

2022-05-11 15:09 UTC, alinelariguet commented on projects/portal/src/app/theme-builder/theme-builder.component.html
> +        <label for="colorCheckbox" class="po-mr-2 po-ml-1">Cor principal: </label>
esse color picker não está alterando a cor do checkbox

2022-05-11 15:21 UTC, alinelariguet commented
Foram levantados os seguintes pontos:
- Alterar o nome para 'Construtor de temas'
- Ao clicar em voltar dee aplicar o reset css antes 
- botão de voltar a cor da fonte está rosa, para seguir o padrão deve ser o roxo
- Botões de 'reset css, 'ver css' e 'configuração está pegando o estilo somente qdo troca a secundária e não pega qdo customiza o hover. Padronizar, ou deixa ele pegar o estilo da customização completa ou então não pega customização nenhuma assim como o voltar.

2022-05-11 15:21 UTC, alinelariguet requested changes
Pontos levantados nos comentários.

2022-05-11 22:05 UTC, alinelariguet approved these changes

2022-05-12 12:15 UTC, brunoromeiro approved these changes

2022-05-12 12:36 UTC, jribeiroo submitted a review, later dismissed

2022-06-08 17:10 UTC, brunoromeiro submitted a review, later dismissed

2022-06-09 20:04 UTC, jribeiroo approved these changes

2022-08-16 13:08 UTC, jhosefmarks commented
Essa PR vai pro ar ainda?

2022-12-29 14:57 UTC, jribeiroo approved these changes

2023-02-03 21:57 UTC, alinelariguet approved these changes

2023-02-03 21:59 UTC, rafaellmarques approved these changes

2023-02-03 21:59 UTC, merged