fix(table): alinha colunas do header
po-ui/po-angular pull request #1300
Opened 2022-06-06 17:46 UTC by jcorrea97

Alinha colunas do header quando a tabela possui `p-height`

**Table**

**DTHFUI-6095**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
colunas da tabela estão ficando desalinhada quando possui p-height

**Qual o novo comportamento?**
colunas da tabela estão ficando alinhadas quando possui p-height

**Simulação**
utilizar app e testar samples do portal:
[app.zip](https://github.com/po-ui/po-angular/files/8846442/app.zip)

2022-06-09 19:58 UTC, jribeiroo approved these changes

2022-06-09 19:59 UTC, gabrielibarbosa approved these changes

2022-06-10 13:57 UTC, alinelariguet requested changes
Ao utilizar a propriedade p-hide-columns-manager a quebra continua em tabelas com altura definida e uma única ação

![Captura de Tela 2022-06-10 às 10 48 56 AM](https://user-images.githubusercontent.com/42390783/173081489-ffe8e41e-c0e3-4dd7-9082-10fdedaa8883.png)

2022-06-10 18:09 UTC, gabrielibarbosa approved these changes

2022-06-10 18:29 UTC, jribeiroo approved these changes

2022-06-10 20:20 UTC, alinelariguet approved these changes

2022-06-10 20:20 UTC, merged