refactor(button): remove a propriedade `p-auto-focus`
po-ui/po-angular pull request #1313
Opened 2022-06-15 14:55 UTC by jribeiroo

**PO-BUTTON, PO-FIELD**

**DTHFUI-6213**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [x] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
Componentes `po-button` e `po-field` possuem propriedade `p-auto-focus` que comprometem questões de acessibilidade.

**Qual o novo comportamento?**
Componentes `po-button` e `po-field` deixam de ter propriedade `p-auto-focus`.

**Simulação**
Rodar o portal

2022-06-17 12:20 UTC, gabrielibarbosa commented
Jorge, é necessário apenas criar uma commit para cada alteração de remoção. Um para button, field, directiva e o documentação do portal.

2022-06-21 11:57 UTC, jcorrea97 submitted a review, later dismissed

2022-07-01 11:34 UTC, alinelariguet requested changes
é necessário alterar o arquivo de breaking changes

2022-07-01 18:53 UTC, jcorrea97 submitted a review, later dismissed

2022-07-01 18:57 UTC, jcorrea97 approved these changes

2022-07-01 20:48 UTC, gabrielibarbosa approved these changes

2022-07-01 21:25 UTC, alinelariguet approved these changes

2022-07-01 21:25 UTC, merged