feat(page-dynamic-table): adiciona propriedade para fixar filtros
po-ui/po-angular pull request #1337
Opened 2022-07-11 18:32 UTC by Kleger

**po-page-dynamic-table**

**Fixes #1287**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [x] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [x] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [x] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [x] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [x] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
No template Page Dynamic Table não é possível ocultar filtros no filtro avançado como é possível com o Page Dynamic Search através da propriedade visible. No Page Dynamic Table a propriedade visible é utilizada apenas na table e todos os fields com propriedade filter:true são repassadas para o Page Dynamic Search como visible:true.

**Qual o novo comportamento?**
Foi criada a propriedade fixed na interface PoPageDynamicTableFilters que será usada em conjunto com as propriedades
filter e initValue, com o objetivo de ocultar o filtro na tela de filtro avançado, porém, mantendo o filtro na consulta das informações.

**Simulação**
Pode ser testado no sample PO Page Dynamic Table - Users. Em "Outras ações" há a opção "Fixed Filter" que irá fixar o filtro search com a informação "Joinville". Então o conteúdo será filtrado, porém o filtro não ficará disponível para ser alterado na tela de filtros avançados. Ao clicar em "Not Fixed Filter" a tela retorna para o padrão inicial apresentando o campo search na tela de filtros avançados.
Obs.: Não foi tratado nessa issue a opção de ocultar a opção fechar do disclaimer. Essa implementação foi realizada na issue #1306 e será utilizada outra propriedade para essa tratativa.

2022-07-22 19:57 UTC, alinelariguet approved these changes

2022-07-25 18:34 UTC, jribeiroo submitted a review, later dismissed

2022-07-25 19:28 UTC, alinelariguet commented
Boa tarde @Kleger , tudo bem?
Houve uma atualização nos pacotes do Angular e tivemos que ajustar um teste, justamente esse teste que está falhando na sua PR, já foi feito o ajuste, porém sua branch agora está desatualizada e por isso o CI não está passando. Por favor atualiza a branch e sobre novamente que já aprovamos. Nós vimos também a necessidade de ajustar a mensagem de commit, até íamos aprovar assim mesmo, porém como deu esse erro nos testes dai peço que você já faça o ajuste. Atualmente a mensagem de commit está duplicada.
Obrigada pela contribuição e pela compreensão.

2022-07-25 19:29 UTC, alinelariguet requested changes
Alterações solicitadas no comentário anterior.

2022-07-26 14:43 UTC, Kleger commented
> Alterações solicitadas no comentário anterior.



> Alterações solicitadas no comentário anterior.



> Alterações solicitadas no comentário anterior.

Bom dia @alinelariguet ,
Atualizei a branch, fiz o rebase e corrigi o texto do commit, porém ainda está com erros nos testes e pelo que vi não é relacionado as alterações que fiz. Poderia verificar?

2022-07-31 23:28 UTC, alinelariguet approved these changes

2022-08-01 11:35 UTC, jribeiroo approved these changes

2022-08-01 11:54 UTC, merged