fix(dynamic-form): ajusta o `OnTouched` do campo
po-ui/po-angular pull request #1379
Opened 2022-08-25 18:49 UTC by wsteixeira

Foi ajustado o `OnTouched` para que o evento `change` seja disparado corretamente, pois o mesmo só é disparado após o campo ser tocado.

Fixes #1378, DTHFUI-6477

**Dynamic Form**

**1378**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O evento `change` não dispara quando o combo é o primeiro campo a ser tocado e alterado

**Qual o novo comportamento?**
O evento `change` dispara quando o combo for tocado e alterado independente da ordem de alteração dos campos.

**Simulação**
Pode ser feita pelo portal ou pelo [APP](https://github.com/po-ui/po-angular/files/9427473/app.zip).

2022-09-23 12:27 UTC, brunoromeiro approved these changes

2022-10-06 12:54 UTC, wsteixeira commented
Conflito resolvido!!

2022-10-06 23:10 UTC, alinelariguet approved these changes

2022-10-06 23:11 UTC, alinelariguet requested changes
Necessário alterar a mensagem principal do commit para [fix(**select**): ajusta o OnTouched do campo] já que as alterações foram feitas diretamente no po-select.

2022-10-07 13:58 UTC, alinelariguet approved these changes

2022-10-07 17:21 UTC, rafaellmarques approved these changes

2022-10-07 17:21 UTC, jcorrea97 approved these changes

2022-10-07 17:23 UTC, merged