docs(guia de migração do PO-UI): corrige o nome da dependência
po-ui/po-angular pull request #1387
Opened 2022-09-02 16:25 UTC by guilnorth

No Guia Migração do PO UI o pacote @po-ui/ng-components está escrito
com grafia errada, possuindo a letra "e" a mais gerando erro na instalação.

**< Guia Migração do PO UI >**

**< NÚMERO DA ISSUE >**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
No Guia Migração do PO UI o pacote @po-ui/ng-components está escrito com grafia errada, possuindo a letra "e" o que gera erro na instalação.

**Qual o novo comportamento?**
Corrigida a grafia no nome do pacote.

**Simulação**

2022-09-02 22:03 UTC, alinelariguet approved these changes

2022-09-05 12:26 UTC, alinelariguet commented
Bom dia @guilnorth, está dando erro de lint no commit, verifique o erro e ajuste a mensagem de commit por favor.

2022-09-05 12:26 UTC, alinelariguet requested changes
necessário ajuste da mensagem de commit

2022-09-08 17:53 UTC, guilnorth commented
> necessário ajuste da mensagem de commit

2022-09-08 17:54 UTC, guilnorth commented
> @alinelariguet corrigida a mensagem de commit


@alinelariguet corrigida a mensagem de commit

2022-09-08 18:16 UTC, guilnorth commented
> necessário ajuste da mensagem de commit

@alinelariguet corrigida a mensagem de commit

2022-09-09 18:29 UTC, alinelariguet commented
Boa tarde @guilnorth, tudo bem?
Agora são 3 commits na PR e o erro do commit lint continua. É necessário fazer um `rebase -i master` para fazer o squash dos commits mantendo somente 1 commit no final e com a mensagem ajustada. Se precisar de apoio é só entrar em contato com a gente.

2022-09-09 18:30 UTC, alinelariguet commented
a mensagem principal do seu commit pode ser: docs(migration): corrige o nome da dependência

2022-09-12 20:21 UTC, guilnorth commented
> Boa tarde @guilnorth, tudo bem? Agora são 3 commits na PR e o erro do commit lint continua. É necessário fazer um `rebase -i master` para fazer o squash dos commits mantendo somente 1 commit no final e com a mensagem ajustada. Se precisar de apoio é só entrar em contato com a gente.

Pronto!

2022-09-19 19:33 UTC, brunoromeiro approved these changes

2022-09-19 19:55 UTC, alinelariguet approved these changes

2022-09-19 19:55 UTC, merged