feat(textarea): aplica estilo e acessibilidade definidos pelo DS
po-ui/po-angular pull request #1394
Opened 2022-09-09 21:24 UTC by brunoromeiro

**TEXTAREA**

**DTHFUI-6442**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
O componente não apresenta o estilo definido pelo design system e não segue as regras de acessibilidade.

**Qual o novo comportamento?**
O componente apresenta novo estilo definido pelo design system e segue as regras de acessibilidade.

**Simulação**
Simular no [app.zip](https://github.com/po-ui/po-angular/files/9538860/app.zip) e no portal.

https://github.com/po-ui/po-style/pull/340

https://github.com/totvs/po-theme-totvs/pull/176

2022-09-15 20:15 UTC, rafaellmarques approved these changes

2022-09-15 20:16 UTC, jcorrea97 submitted a review, later dismissed

2022-09-25 17:20 UTC, alinelariguet commented
Não consegui aplicar o placeholder no app, somente no labs, não entendi. Montei o ambiente várias vezes e não aplicou no app. Utilizei o app da PR e também não foi possível aplicar o placeholder.

2022-09-25 17:21 UTC, alinelariguet commented
Conforme handoff ao desabilitar o textarea não deve ser aplciado o placeholder. O Comportamento ocorre no labs.

2022-09-25 17:26 UTC, alinelariguet requested changes
verificar comentários anteriores.

2022-09-25 22:29 UTC, alinelariguet approved these changes

2022-09-25 22:39 UTC, jcorrea97 approved these changes

2022-09-25 22:42 UTC, merged