build: atualização para o angular 15
po-ui/po-angular pull request #1567
Opened 2022-12-08 14:38 UTC by jcorrea97

atualização para o angular 15

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

 atualização para o angular 15

2022-12-09 20:11 UTC, alinelariguet commented on docs/guides/migration-poui.md
>  Por exemplo:
Precisamos deixar de forma muito clara e chamando a atenção que o ng update da versão 15 next está em desenvolvimento ainda.

2022-12-09 20:27 UTC, alinelariguet commented
Necessário ajuste no guia https://po-ui.io/guides/browser-support conforme documantação do angular (principalmente no que se trata de android) https://angular.io/guide/browser-support

2022-12-09 21:58 UTC, alinelariguet commented
alterar a versão da dependencia "ngx-markdown": "~14.0.1", para "ngx-markdown": "~15.0.0", pois está ocorrendo problema ao subir uma nova aplicação com PO UI.

2022-12-09 22:11 UTC, alinelariguet requested changes
comentários acima

2022-12-13 16:22 UTC, rafaellmarques commented on projects/templates/package.json
> +    "@angular/compiler": "^15.03",
```suggestion
    "@angular/compiler": "^15.0.3",
```

2022-12-15 19:07 UTC, jribeiroo approved these changes

2022-12-15 19:10 UTC, alinelariguet commented on README.md
> +    "@angular/router": "^15.0.3",
```suggestion
    "@angular/animations": "~15.0.3",
    "@angular/common": "~15.0.3",
    "@angular/compiler": "~15.0.3",
    "@angular/core": "~15.0.3",
    "@angular/forms": "~15.0.3",
    "@angular/platform-browser": "~15.0.3",
    "@angular/platform-browser-dynamic": "~15.0.3",
    "@angular/router": "~15.0.3",
```

2022-12-16 14:22 UTC, alinelariguet approved these changes

2022-12-16 14:23 UTC, rafaellmarques approved these changes

2022-12-16 14:23 UTC, merged