feat(menu): permite habilitar o automatic toggle
po-ui/po-angular pull request #1909
Opened 2023-12-18 19:12 UTC by anliben

Permite habilitar o automatic toggle no componente `po-menu`

**menu**

**DTHFUI-8037**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
Menu colapsa e expande a partir de um evento de hover no menu

**Qual o novo comportamento?**
Propriedade que permite colapsar e expandir partir de um evento de hover no menu

**Simulação**
portal ou sample labs

2023-12-19 19:49 UTC, felipepetuco approved these changes

2024-01-11 18:46 UTC, jcorrea97 requested changes

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
> +    it('automaticToggle: shoud set property with true', () => {
remover teste

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/po-menu-base.component.spec.ts
> +    it('automaticToggle: shoud set property with false', () => {
remover teste

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/po-menu-base.component.ts
> +  @Input('p-automatic-toggle') automaticToggle: boolean = false;
```suggestion
  @Input({ alias: 'p-automatic-toggle', transform: convertToBoolean }) automaticToggle: boolean = false;

```

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
> +    [p-automatic-toggle]="automaticToggle"
remover propriedade do labs

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.html
> +        <po-switch
remover switch do labs

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
> +  automaticToggle: boolean = false;
remover

2024-01-11 18:46 UTC, jcorrea97 commented on projects/ui/src/lib/components/po-menu/samples/sample-po-menu-labs/sample-po-menu-labs.component.ts
> +    this.automaticToggle = false;
remover

2024-01-11 19:22 UTC, jcorrea97 approved these changes

2024-01-11 19:48 UTC, felipepetuco approved these changes

2024-01-12 17:33 UTC, merged