fix(dynamic-view) Correção campos duplicados no dynamicview
po-ui/po-angular pull request #2001
Opened 2024-03-14 19:10 UTC by bruno-severino

**po-dynamic-view **

**8512**
_____________________________________________________________________________

**PR Checklist [Revisor]**

- [ ] [Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
- [ ] [Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
- [ ] Testes unitários (Cobre a situação implementada e coverage está mantido)
- [ ] [Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
- [ ] [Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
- [ ] Rodado em navegadores suportados (Chrome, FireFox, Edge)

**Qual o comportamento atual?**
Ocorre uma duplicação de alguns campos mostrados no dynamicview, quando esses campos não possue valor ou eles estão com visibilidade falsa

**Qual o novo comportamento?**
correção feita, não ocorre mais a duplicata dos campos

**Simulação**
- Abrir na documentação [PO-UI > dynamic view](https://po-ui.io/documentation/po-dynamic-view). O Ultimo exemplo tem campos com visible false, que estava duplicando o campo 'city'
- anexo 
[simulação.zip](https://github.com/po-ui/po-angular/files/14606977/simulacao.zip)
Existe campo sem valores que estava duplicado o campo 'partner'

2024-03-15 04:46 UTC, carlosdiego requested changes

2024-03-15 04:46 UTC, carlosdiego commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
>          newFields.push(this.createField(tempField));
Com essas modificações a questão da ordenação foi resolvida porem percebi que o um outro erro persiste, campos que dependem de **optionsService** ou **searchService** falham ao carregar dados no **dynamic-view**. Isso se deve à condição no método **[transformFieldLabel](https://github.com/po-ui/po-angular/blob/a74930c9dbfc6d9ef557b80f86a41f1242f9c513/projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts#L349)** acionado dentro do [createField](https://github.com/po-ui/po-angular/blob/a74930c9dbfc6d9ef557b80f86a41f1242f9c513/projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts#L231C20-L231C39), que inadvertidamente anula o valor da propriedade, bloqueando o carregamento em **dynamic-view**. Uma revisão crítica é necessária, principalmente nas linhas 348,349 e 350, onde a lógica pode estar mal aplicada, sugerindo que a substituição do valor baseada no label pode ser desnecessária pois tal valor já existe na propriedade.
Observe que o único cenário que essa logica atende é quando o **fieldLabel** possui o mesmo nome da **property**.

2024-03-18 20:17 UTC, pedrodominguesp requested changes

2024-03-18 20:17 UTC, pedrodominguesp commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.ts
> +   * Se não achar no index, é adiciona +1 até achar uma proxima posição
Verificar se existe a necessidade de manter esse comentário.
Se o código estiver legível, o comentário é desnecessário.

Se manter o comentário, arrumar os erros de gramática.

2024-03-18 20:17 UTC, pedrodominguesp commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
> +    it('should return ordering field when have duplicated order', () => {
Sobre o uso da palavra when:

Nesse caso, ambas as palavras podem ser usadas, mas elas trazem uma nuance ligeiramente diferente para a frase.

Usar "when" sugere uma situação em que a ocorrência é vista como algo que acontece em circunstâncias específicas, mas não necessariamente limitada a condições. Pode indicar uma expectativa de que, em algum momento, haverá ordens duplicadas, e quando isso acontecer, o campo de ordenação deve ser retornado. É mais sobre o tempo ou a circunstância.

Usar "if" traz uma conotação de condição, indicando que somente sob a condição de haver ordens duplicadas é que o campo de ordenação será retornado. Isso implica uma possibilidade, mas não uma certeza de que as ordens duplicadas ocorrerão.

Se você deseja enfatizar a condição para a ação de retornar o campo de ordenação, "if" seria mais apropriado. Por outro lado, se a ideia é destacar a situação ou o momento em que as ordens duplicadas ocorrem, mantendo uma leve implicação de que isso provavelmente acontecerá, então "when" pode ser a escolha certa.

Baseando-se na precisão técnica e clareza, especialmente em documentações ou instruções de programação, "if" pode ser ligeiramente preferível para enfatizar a condição sob a qual o campo de ordenação deve ser retornado.

2024-03-18 20:22 UTC, pedrodominguesp commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-view/po-dynamic-view-base.component.spec.ts
> +    it('should return ordering field when have duplicated order', () => {
antes da descrição do teste, incluir o nome do teste a ser testado.

2024-03-19 21:27 UTC, closed without merging