feat(combo): adiciona a propriedade p-clean
po-ui/po-angular pull request #326
Opened 2020-03-17 13:33 UTC by diegoalexandrooliveira

**po-combo**

**DTHFUI-2314**
_____________________________________________________________________________

**PR Checklist**

- [X] Código
- [X] Testes unitários
- [X] Documentação
- [X] Samples

**Qual o comportamento atual?**
Para limpar o combo, é necessário apagar todos caracteres do input.

**Qual o novo comportamento?**
Ao atribuir o valor true para a propriedade p-clean e selecionar um item no combo, será exibido um ícone X. Ao clicar neste ícone, o combo será limpo.

**Simulação**
Criar um po-combo com a propriedade p-clean, escolher alguma opção do combo e clicar no X ao lado da seta. O combo deve ser limpo e o ngModel deve ser atualizado

2020-06-01 17:58 UTC, FelipeGatti commented
Creio que seria necessário também uma opção para sobrescrever o comportamento atual de manter a lista quando o filter retornar uma lista vazia.
Hoje a ultima lista filtrada continua sendo exibida mesmo se o serviço retornar null, undefined ou [].
Desta maneira nunca será exibido o "noData" do literals caso seja carregado algo em algum momento.

2020-07-31 18:31 UTC, jhonyeduardo commented
Olá diego,

Vamos avaliar com equipe de UX a possibilidade de inclusão da opção de clean no componente combo.

Qualquer dúvida, estamos a disposição.

2020-09-03 19:14 UTC, jhosefmarks commented
#152

2020-09-04 14:57 UTC, jhosefmarks requested changes
Necessário atualizar PR.

2020-09-05 12:24 UTC, diegoalexandrooliveira commented
Irei refazer em outro PR para evitar os possíveis conflitos ao atualizar esta branch.

2020-09-05 12:24 UTC, closed without merging