feat(dynamic-table): exibe o filtro mesmo que o campo esteja invisível
po-ui/po-angular pull request #598
Opened 2020-09-03 19:51 UTC by jhonyeduardo

**DYNAMIC TABLE**

**DTHFUI-4135 e DTHFUI-4119**
_____________________________________________________________________________

**PR Checklist**

- [ ] Código
- [ ] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
- Exibe o botão "Novo" caso informar objeto que não possua a propriedade `new`;
- Não exibia o campo na busca avançada caso informasse visible: true;

O componente estava muito lento, devido aos `gets` que estavam sendo utilizados.

**Qual o novo comportamento?**
- Não exibe o botão "Novo" caso não informar
valor na propriedade actions.new.
- Adiciona a propriedade PoPageDynamicField. AllowColumnsManager,
que permite visualiza-lo no gerenciador de colunas
mesmo estando visible: false;
- Exibe o filtro mesmo que o campo esteja invisivel na
tabela (visible=false);
- Melhora a performance do componente, eliminando os gets que eram repassados ao template.

**Simulação**
- Utilizar Sample do Portal, e;

```
const routes = [
  {
    path: 'custom',
    component: SamplePoPageDynamicTableUsersComponent
  },
  {
    path: 'dynamic',
    component: PoPageDynamicTableComponent,
    data: {
      serviceApi: 'https://po-sample-api.herokuapp.com/v1/people',
      serviceMetadataApi: 'http://demo4164369.mockable.io/metadata' // INFORME UM METADATA QUE RETORNE OS CAMPOS COM A NOVA REGRA/PROPRIEDADE.
    }
  }
];
```

2020-09-03 20:32 UTC, alvarocamillont requested changes

2020-09-03 20:32 UTC, alvarocamillont commented on projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
> +      .map(filterField => ({ ...filterField, visible: true }));
Eu não entendi pq vc colocou de forma explicita que todo o campo se nao informar nada sera visible true

2020-09-04 12:40 UTC, jhonyeduardo commented on projects/templates/src/lib/components/po-page-dynamic-table/po-page-dynamic-list-base.component.ts
> +      .map(filterField => ({ ...filterField, visible: true }));
No caso do filtros, todos serão exibidos, caso possuir filter: true

2020-09-04 19:35 UTC, alvarocamillont submitted a review, later dismissed

2020-09-04 20:28 UTC, nicoleoliveira approved these changes

2020-09-04 20:37 UTC, alvarocamillont approved these changes

2020-09-04 20:38 UTC, merged