feat(page-dynamic-search): adiciona propriedade p-quick-search-width
po-ui/po-angular pull request #604
Opened 2020-09-08 20:28 UTC by samir-ayoub

**page-dynamic-search**
**page-dynamic-table**

**DTHFUI-4118**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [x] Samples

**Qual o comportamento atual?**
O componente `po-page-list` possui propriedade para definição de largura do campo de busca porém não recebe o repasse para tal no template `page-dynamic-search`.

**Qual o novo comportamento?**
O desenvolvedor agora pode definir uma largura para o campo de busca rápida nos templates `page-dynamic-search` e `page-dynamic-table`.

**Simulação**
Samples de uso dos templates.

2020-09-09 13:54 UTC, nicoleoliveira approved these changes

2020-09-09 14:26 UTC, jhonyeduardo requested changes
- Implementar a propriedade nova para utilizar com metadados e load; (adicionar na interface)
- Criar mais um commit para o dynamic-table;
 ex : feat(page-dynamic-search): adiciona a propriedade ...
       feat(page-dynamic-table): adiciona a propriedade ...

2020-09-09 20:36 UTC, jhonyeduardo approved these changes

2020-09-10 11:45 UTC, nicoleoliveira approved these changes

2020-09-10 13:21 UTC, jhosefmarks approved these changes

2020-09-10 13:22 UTC, merged