Build 10 1/dthfui 4189
po-ui/po-angular pull request #611
Opened 2020-09-16 12:48 UTC by alvarocamillont

**< COMPONENTE >**

**< NÚMERO DA ISSUE >**
_____________________________________________________________________________

**PR Checklist**

- [ ] Código
- [ ] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**

**Qual o novo comportamento?**

**Simulação**

2020-09-17 18:00 UTC, nicoleoliveira reviewed
Faltou modificar as documentações com as novas versões:
- https://po-ui.io/guides/sync-get-started
- https://po-ui.io/guides/getting-started

2020-09-17 18:18 UTC, samir-ayoub commented on projects/ui/src/lib/components/po-chart/po-chart-types/po-chart-dynamic-type.component.ts
> +  protected getSeriesWithValue(value) {
suprimir esse método já que ele não faz nada. E no `po-chart-circular` pode removê-lo também assim como os testes unitários relacionados com ele.

2020-09-17 20:16 UTC, samir-ayoub commented on docs/guides/sync-get-started.md
> +    "@angular/common": "~10.0.0",
corrigir versões, comparar com o getting-started.md

2020-09-17 20:16 UTC, samir-ayoub commented on docs/guides/sync-get-started.md
> +    "@angular-devkit/build-angular": "~0.1000.0",
corrigir versões, inclusive do typescript

2020-09-17 20:23 UTC, alvarocamillont commented on docs/guides/sync-get-started.md
> +    "@angular/common": "~10.0.0",
Olá conforme conversado com a @nicoleoliveira  o ionic cli, com o angular cli 10.1.0 sobe um projeto nessa versao por isso que eu mantive. como já saiu a versao 6 e iremos analisar o seu impacto no ng sync a gente vai reavaliar nessa tarefa futura.

2020-09-17 20:23 UTC, alvarocamillont commented on docs/guides/sync-get-started.md
> +    "@angular-devkit/build-angular": "~0.1000.0",
Olá conforme conversado com a @nicoleoliveira  o ionic cli, com o angular cli 10.1.0 sobe um projeto nessa versao por isso que eu mantive. como já saiu a versao 6 e iremos analisar o seu impacto no ng sync a gente vai reavaliar nessa tarefa futura.****

2020-09-17 20:51 UTC, jhonyeduardo commented on docs/guides/getting-started.md
> +npm i -g @angular/cli
Sugestão:
Fixar para quando sair a versão 11 não termos problemas.

2020-09-17 20:51 UTC, jhonyeduardo commented on docs/guides/getting-started.md
> +yarn global add @angular/cli
Sugestão:
Fixar para quando sair a versão 11 não termos problemas.

2020-09-17 21:32 UTC, alvarocamillont commented on docs/guides/getting-started.md
> +npm i -g @angular/cli
Resolvido

2020-09-17 21:32 UTC, alvarocamillont commented on docs/guides/getting-started.md
> +yarn global add @angular/cli
Resolvido

2020-09-18 12:01 UTC, samir-ayoub approved these changes

2020-09-18 12:30 UTC, jhonyeduardo commented on projects/sync/package.json
> +    "@ionic-native/core": "^5.23.0",
Ionic faz o standard version corretamente, sem quebrar no minor version?

2020-09-18 17:36 UTC, nicoleoliveira requested changes

2020-09-18 17:36 UTC, nicoleoliveira commented on docs/guides/sync-get-started.md
> +    "@ionic/angular": "5.23.0",
A versão 5.23.0 ainda não foi lançada, mas pode ser utilizado a versão abaixo:
```suggestion
    "@ionic/angular": "5.3.3",
```

2020-09-18 17:50 UTC, nicoleoliveira approved these changes

2020-09-18 17:52 UTC, samir-ayoub approved these changes

2020-09-18 18:14 UTC, jhosefmarks approved these changes

2020-09-18 18:15 UTC, merged