fix(ui/templates): ajusta declaracao incorreta dos event emitter
po-ui/po-angular pull request #627
Opened 2020-09-30 21:14 UTC by siegklenes

Ajusta a declaração incorreta nos projetos ui e templates dos eventemitter.

**< DTHFUI-4309 >**
_____________________________________________________________________________

**PR Checklist**

- [ ] Código
- [ ] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
Não permite o uso do po-ui com strict mode ativo

**Qual o novo comportamento?**
Permite o uso do po-ui com strict mode ativo

**Simulação**
ng new strict-po --strict=true --skipTests=true --skipInstall=true
#altera o package.json conforme guia de instalação
npm i
ng add @po-ui/ng-components
cria a function fn no home component ts
inclui no home component html <po-table (p-show-more)="fn()"></po-table>
ng build --prod

no console, Object is possibly 'undefined'

2020-09-30 21:19 UTC, jhosefmarks commented
Ao remover o operador `?` você está tornando as propriedades obrigatórias. Creio que essa não seja a melhor opção, ou tenham outros efeitos colaterais indesejados.

2020-09-30 22:41 UTC, alvarocamillont commented
> Ao remover o operador `?` você está tornando as propriedades obrigatórias. Creio que essa não seja a melhor opção, ou tenham outros efeitos colaterais indesejados.

O Output no angular é opcional (Testei aqui hehe)  @siegklenes sua alteração faz sentido e vamos analisá-la! Muito obrigado!

2020-10-01 14:53 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
>    /** Função chamada ao clicar no ícone de configuração */
O `?` era utilizado para documentação também, com isso no Portal aparecia `(opcional)`.
Com essa atualização os eventos não apresentarão mais o `opcional`.

Mas tem também como fazer via documentação, veja abaixo:

```suggestion 
 /**
   * @optional
   *
   * @description
   * Função chamada ao clicar no ícone de configuração
   */
```

2020-10-01 21:47 UTC, siegklenes commented on projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
>    /** Função chamada ao clicar no ícone de configuração */
Pronto!

2020-10-02 14:42 UTC, alvarocamillont requested changes

2020-10-02 14:42 UTC, alvarocamillont commented on projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
>    /** Função que será chamada ao clicar no título. */
Faltou a doc optional aqui :)

2020-10-02 14:51 UTC, jhonyeduardo submitted a review, later dismissed

2020-10-02 14:57 UTC, siegklenes commented on projects/ui/src/lib/components/po-widget/po-widget-base.component.ts
>    /** Função que será chamada ao clicar no título. */
Resolvido em https://github.com/po-ui/po-angular/pull/627/commits/1d821d96ad3d5c1e7e2f82820d85aa2dd75b2581

2020-10-02 17:00 UTC, jhonyeduardo approved these changes

2020-10-02 17:27 UTC, alvarocamillont approved these changes

2020-10-02 17:28 UTC, merged