feat(table): inclui evento `p-change-visible-columns`
po-ui/po-angular pull request #640
Opened 2020-10-21 20:10 UTC by alinelariguet

**PO-TABLE E PO-POPOVER**

**DTHFUI-3699**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [ ] Samples

**Qual o comportamento atual?**
Hoje não é possível saber quais colunas que o usuário configurou para ficar visível.

**Qual o novo comportamento?**
Criado evento `p-change-visible-columns` que será disparado ao alterar as colunas visíveis no gerenciador de colunas e fechar o popover do gerenciador.

**Simulação**
- app.component.html:
```
<po-table
  [p-columns]="hiringProcessesColumns"
  [p-items]="hiringProcesses"
  (p-change-visible-columns)="myOnChangeVisibleColumns($event)"
>
</po-table>
```

- app.component.ts:
```
  hiringProcesses: Array<object>;
  hiringProcessesColumns: Array<PoTableColumn>;

  constructor() {}

  ngOnInit() {
    this.hiringProcesses = this.getItems();
    this.hiringProcessesColumns = this.getColumns();

  }

  myOnChangeVisibleColumns(event) {
    console.log('visible columns', event);
  }

  getColumns(): Array<PoTableColumn> {
    return [
      {
        property: 'hireStatus',
        label: 'Status',
        type: 'subtitle',
        subtitles: [
          { value: '1', color: 'success', label: 'Hired', content: '1' },
          { value: '2', color: 'warning', label: 'Progress', content: '2' },
          { value: '3', color: 'danger', label: 'Canceled', content: '3' }
        ]
      },
      { property: 'idCard', label: 'Identity card', type: 'string' },
      { property: 'name', label: 'Name' },
      { property: 'age', label: 'Age' },
      { property: 'city', label: 'City' },
      { property: 'jobDescription', label: 'Job description', type: 'string' }
    ];
  }

  getHireStatus() {
    return [
      { value: '1', label: 'Hired' },
      { value: '2', label: 'Progress' },
      { value: '3', label: 'Canceled' }
    ];
  }

  getItems() {
    return [
      {
        hireStatus: '1',
        name: 'James Johnson',
        city: 'Ontario',
        age: 24,
        idCard: 'AB34lxi90',
        job: 'abc',
        jobDescription: 'Systems Analyst'
      },
      {
        hireStatus: '2',
        name: 'Brian Brown',
        city: 'Buffalo',
        age: 23,
        idCard: 'HG56lds54',
        job: 'def',
        jobDescription: 'Trainee'
      },
    ];
  }

  getJobs() {
    return [
      { value: 'abc', label: 'Systems Analyst' },
      { value: 'def', label: 'Trainee' },
    ];
  }
```

2020-10-22 12:52 UTC, samir-ayoub approved these changes

2020-10-22 19:50 UTC, jhonyeduardo requested changes
O evento (p-change-visible-columns) está sendo disparado na primeira vez, ao fechar o popover, sem manipulação.

2020-10-23 18:03 UTC, samir-ayoub approved these changes

2020-10-26 01:22 UTC, jhonyeduardo approved these changes

2020-10-26 11:21 UTC, samir-ayoub approved these changes

2020-10-26 11:21 UTC, merged