Page dynamic search/dthfui 2726
po-ui/po-angular pull request #649
Opened 2020-10-28 11:42 UTC by samir-ayoub

**page-dynamic-search**

**DTHFUI-2726**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [ ] Samples

**Qual o comportamento atual?**
Quando um dos filters usa o combo, o mesmo exibe os valores selecionados e não a descrição que o usuário usou para fazer o filtro.

**Qual o novo comportamento?**
Quando o usuário usar um combo para fazer um filtro, o disclaimer deve exibir a descrição do item selecionado e não o valor "interno". 

**Simulação**

2020-10-28 15:08 UTC, alvarocamillont submitted a review, later dismissed

2020-10-28 22:36 UTC, jhonyeduardo requested changes
O valor internamente deve-se manter o mesmo, utilizando o value.

A label deve ser apenas na apresentação.

![image](https://user-images.githubusercontent.com/6907801/97503912-b0daab00-1954-11eb-9a56-22e5990798e9.png)

2020-10-29 20:06 UTC, alvarocamillont commented
![image](https://user-images.githubusercontent.com/17092119/97626741-0d979d80-1a09-11eb-8b88-1f3d35570f08.png)
Resolvido

2020-10-29 20:06 UTC, alvarocamillont approved these changes

2020-10-29 21:38 UTC, jhonyeduardo approved these changes

2020-10-29 21:56 UTC, merged