feat(lookup): adicionar evento p-change
po-ui/po-angular pull request #664
Opened 2020-11-12 03:46 UTC by tolentinos

O evento p-change será disparado ao alterar o ngModel. É uma função que será disparada quando houver alterações.

Fixes TIS-1

**po-lookup**

**TIS-1**
_____________________________________________________________________________

**PR Checklist**

- [X] Código
- [X] Testes unitários
- [X] Documentação
- [X] Samples

**Qual o comportamento atual?**
Não havia o evento change no componente

**Qual o novo comportamento?**
Criação do evento p-change, que deverá ser disparado toda vez que o model for alterado.

**Simulação**
Esta correção pode ser validada utilizando o sample labs no portal.

2020-11-12 13:17 UTC, jhosefmarks commented
Qual a diferença para o p-selected? Quando um vai ser disparado e o outro não?

2020-11-12 19:28 UTC, tolentinos commented
O p-selected é disparado apenas quando há uma seleção, se ele perder a
seleção não realiza nenhum disparo.

O p-change é chamado sempre que houver mudança no model, ou seja, alterou
esse evento é disparado.

Boa parte das vezes os 2 eventos serão executados, porque aconteceu seleção
e consecutivamente teve alteração do model.

*Atenciosamente,
                  *
*______________________________________*
*Vinícius **Tolentino*
Unidade Belo Horizonte / MG / Brasil
( (55 ) (31) 4042-2995 - BRASIL (Whatsapp)
(  (31) 2516-3166
+ vinicius@tolentinos.com
 www.tolentinos.com






Em qui., 12 de nov. de 2020 às 10:17, Jhosef Marks <notifications@github.com>
escreveu:

> Qual a diferença para o p-selected? Quando um vai ser disparado e o outro
> não?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/po-ui/po-angular/pull/664#issuecomment-726071349>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHJPX2FMRZHX5QSCDE467YDSPPN7TANCNFSM4TSYNOLQ>
> .
>

2020-11-12 20:02 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
> +   *  Uma função será disparada quando houver alterações.
Realizar a alteração na documentação para:
```
Evento que será disparado ao alterar o model.

> Por parâmetro será passado o novo valor.
```

1. Utilizar "model ou value", mas ngModel pois o dev pode utilizar ReactiveForm e poderia causar confusão.
2. Importante informar que será passado o novo valor por parâmetro.

2020-11-12 20:06 UTC, tolentinos commented on projects/ui/src/lib/components/po-field/po-lookup/po-lookup-base.component.ts
> +   *  Uma função será disparada quando houver alterações.
Combinado, já iremos realizar os ajustes e reenviar.

2020-11-12 20:39 UTC, jhonyeduardo requested changes
O evento p-change esta sendo disparado mesmo quando o model está com o mesmo valor.

Exemplo com model undefined:
Digitar "abc" e apertar "Tab"
- Será disparado o p-change

Digitar "abc" novamente e apertar "Tab"
- Será disparado o p-change novamente

O change deve acompanhar o model, caso for o mesmo valor que o anterior não deve ser disparado.

Exemplo:
Digitar "abc" e apertar "Tab"
- Não deve disparar o evento

Digitar "abc" novamente e apertar "Tab"
- Não deve disparar o evento

Digitar um valor valido (kakaroto) e apertar "Tab"
- Deve disparar o evento

Com valor selecionado, digitar "abc" e apertar "Tab"
- Deve disparar o evento;

Digitar "abc" novamente e apertar "Tab"
- Não deve disparar o evento

2020-11-12 21:20 UTC, tolentinos commented
Beleza.

vamos realizar esses testes aí.

Obrigado.

Em qui, 12 de nov de 2020 17:39, Jhony Eduardo Senem <
notifications@github.com> escreveu:

> *@jhonyeduardo* requested changes on this pull request.
>
> O evento p-change esta sendo disparado mesmo quando o model está com o
> mesmo valor.
>
> Exemplo com model undefined:
> Digitar "abc" e apertar "Tab"
>
>    - Será disparado o p-change
>
> Digitar "abc" novamente e apertar "Tab"
>
>    - Será disparado o p-change novamente
>
> O change deve acompanhar o model, caso for o mesmo valor que o anterior
> não deve ser disparado.
>
> Exemplo:
> Digitar "abc" e apertar "Tab"
>
>    - Não deve disparar o evento
>
> Digitar "abc" novamente e apertar "Tab"
>
>    - Não deve disparar o evento
>
> Digitar um valor valido (kakaroto) e apertar "Tab"
>
>    - Deve disparar o evento
>
> Com valor selecionado, digitar "abc" e apertar "Tab"
>
>    - Deve disparar o evento;
>
> Digitar "abc" novamente e apertar "Tab"
>
>    - Não deve disparar o evento
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/po-ui/po-angular/pull/664#pullrequestreview-529478992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHJPX2AKVYLOOC6L777BAILSPRBXPANCNFSM4TSYNOLQ>
> .
>

2020-11-13 13:19 UTC, jhonyeduardo commented
Alterar mensagem de commit:

de: feat(lookup): adicionar evento p-change

para: feat(lookup): adiciona evento p-change

https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md#descri%C3%A7%C3%A3o-curta

2020-11-16 15:22 UTC, jhonyeduardo approved these changes

2020-11-16 16:38 UTC, fabiomr78 approved these changes

2020-11-16 17:00 UTC, merged