feat(dynamic-form):  adiciona propriedades as currency, decimals-length, thousand-maxlength e icon
po-ui/po-angular pull request #682
Opened 2020-11-20 05:23 UTC by tolentinos

**dynamic-form**

**TIS-4**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [x] Samples

**Qual o comportamento atual?**
Atualmente não possui as propriedades currency, decimals-length, thousand-maxlength e icon

**Qual o novo comportamento?**
Adiciona propriedades as currency, decimals-length, thousand-maxlength e icon

**Simulação**
<po-dynamic-form [p-fields]="fields"></po-dynamic-form>

...

fields: Array<PoDynamicFormField> = [
  ...
  {
    property: 'wage',
    label: 'Salario',
    currency: true,
    decimalsLength: 3,
    thousandMaxlength: 7,
    icon: 'po-icon-finance'
  },
  ...
];

2020-11-20 12:30 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   */
```
/** 
Define o ícone que será exibido no início do campo.

   * > Esta propriedade o pode ser utilizado nos campos:
   * - Input;
   * - Number;
   * - Decimal;
   * - Combo;
   * 
   * > Veja a disponibilidade de ícones em [biblioteca de ícones](guides/icons).
   */
```

2020-11-20 15:30 UTC, tolentinos commented
Obrigado, vou corrigir e reenviar.

Em sex, 20 de nov de 2020 09:31, Jhony Eduardo Senem <
notifications@github.com> escreveu:

> *@jhonyeduardo* commented on this pull request.
> ------------------------------
>
> In
> projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> <https://github.com/po-ui/po-angular/pull/682#discussion_r527660198>:
>
> > @@ -61,6 +61,29 @@ export interface PoDynamicFormField extends PoDynamicField {
>
>    /** Máscara para o campo. */
>
>    mask?: string;
>
>
>
> +  /** Define o ícone que será exibido no início do campo.
>
> +   * > Esta propriedade so podera ser caso:
>
> +   * - `type` seja *input*;
>
> +   * - `type` seja *number*;
>
> +   * - `type` seja *currency*;
>
> +   * - `type` seja *combo*;
>
> +   * - Não possuir `help` e `label`.
>
> +   * > Veja a disponibilidade de ícones em [biblioteca de ícones](guides/icons).
>
> +   */
>
>
> /**
>
> Define o ícone que será exibido no início do campo.
>
>
>
>    * > Esta propriedade o pode ser utilizado nos campos:
>
>    * - Input;
>
>    * - Number;
>
>    * - Decimal;
>
>    * - Combo;
>
>    *
>
>    * > Veja a disponibilidade de ícones em [biblioteca de ícones](guides/icons).
>
>    */
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/po-ui/po-angular/pull/682#pullrequestreview-535387729>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHJPX2DEHFNNNCVK5L7DUKDSQZORFANCNFSM4T4J7RMQ>
> .
>

2020-11-20 19:05 UTC, jhosefmarks requested changes

2020-11-20 19:05 UTC, jhosefmarks commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   */
Por que não pode ter help e label para usar ícone?

2020-11-20 19:05 UTC, jhosefmarks commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   * > Esta propriedade so pode ser utilizada quando o `type` for *currency*.
Erro ortográfico: so -> só.

2020-11-20 19:05 UTC, jhosefmarks commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   * > Esta propriedade so pode ser utilizada quando o `type` for *currency*.
Erro ortográfico: so -> só.

2020-11-21 00:05 UTC, tolentinos commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   */
A informação estava errada. Mas já corrigi o commit.

2020-11-21 00:05 UTC, tolentinos commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   * > Esta propriedade so pode ser utilizada quando o `type` for *currency*.
corrigido

2020-11-21 00:05 UTC, tolentinos commented on projects/ui/src/lib/components/po-dynamic/po-dynamic-form/po-dynamic-form-field.interface.ts
> +   * > Esta propriedade so pode ser utilizada quando o `type` for *currency*.
corrigido

2020-11-23 12:31 UTC, jhosefmarks approved these changes

2020-11-23 12:39 UTC, jhonyeduardo approved these changes

2020-11-23 12:39 UTC, merged