feat: field-container
po-ui/po-angular pull request #684
Opened 2020-11-20 09:04 UTC by josuedepaula

**po-field-container**

**MDO-39**
_____________________________________________________________________________

**PR Checklist**

- [ X ] Código
- [ X ] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
A literal "Opcional" utilizado no po-field-container não traduz para os idiomas suportados.

**Qual o novo comportamento?**
A literal "Opcional" deverá utilizar no po-field-container as literais para os idiomas suportados.

**Simulação**

2020-11-20 20:59 UTC, jhosefmarks requested changes

2020-11-20 20:59 UTC, jhosefmarks commented on projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.spec.ts
> +    expectBrowserLanguageMethod('pt', component, 'literals.optional', 'Opcional');
Seus testes vão continuar falhando, da uma lida na documentação do método expectBrowserLanguageMethod (util-expect.spec.ts:109).

Uma outra abordagem para testar as literais seria usando o exemplo da PR https://github.com/po-ui/po-angular/pull/488/files, os testes são feitos de outra forma.

2020-11-20 21:48 UTC, jhonyeduardo commented on debug.log
> +[1120/183212.664:ERROR:directory_reader_win.cc(43)] FindFirstFile: O sistema n�o pode encontrar o caminho especificado. (0x3)
Remover este arquivo

2020-11-20 21:56 UTC, jhosefmarks commented on projects/ui/src/lib/components/po-field/po-field-container/po-field-container.component.spec.ts
> -  it('should get pt optional literal', () => {
Por que foram removidos os testes das literais? Isso deixa a parte de literais sem uma cobertura de qualidade.

2020-11-23 02:34 UTC, jhonyeduardo requested changes
Atualmente:
![image](https://user-images.githubusercontent.com/6907801/99924952-e76cd100-2d1a-11eb-82be-9ab71bf0033e.png)

Na branch:
![image](https://user-images.githubusercontent.com/6907801/99924943-e2a81d00-2d1a-11eb-8cb8-e5a341a1f0a3.png)


1. A tradução em russo acabou criando duas linhas, precisa ser ajustada.
2. Com a remoção da função getOptionalText, se perdeu o parenteses.
    - Adiciona-lo em volta da interpolação "({{ literals,optional }})" ou voltar com a função.

2020-11-26 12:25 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-menu/po-menu.component.spec.ts
>        expect(nativeElement.querySelector('po-menu-filter')).toBeFalsy();
Fonte de outro componente

2020-11-26 12:25 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-menu/po-menu.component.ts
>    }
Fonte de outro componente!

2020-11-26 14:43 UTC, jhonyeduardo approved these changes

2020-11-26 16:55 UTC, jhosefmarks approved these changes

2020-11-26 17:02 UTC, merged