docs(http-interceptor): altera endpoint utilizado no sample
po-ui/po-angular pull request #738
Opened 2020-12-16 13:43 UTC by tolentinos

Altera a URL do endpoint messages utilizado no sample.

Fixes DTHFUI-2692

**http-interceptor**

**DTHFUI-2692**
_____________________________________________________________________________

**PR Checklist**

- [ ] Código
- [ ] Testes unitários
- [ ] Documentação
- [x] Samples

**Qual o comportamento atual?**
URL antiga para requisição

**Qual o novo comportamento?**
URL da nova API

**Simulação**

2020-12-16 14:28 UTC, jhosefmarks requested changes

2020-12-16 14:28 UTC, jhosefmarks commented on projects/ui/src/lib/interceptors/po-http-interceptor/samples/sample-po-http-interceptor-labs.component.ts
> +      .post(`http://po-sample-api.herokuapp.com/v1/messages`, body, { headers, params })
Usar HTTPS.

2020-12-20 08:09 UTC, jhonyeduardo approved these changes

2020-12-20 21:14 UTC, jhosefmarks approved these changes

2020-12-20 21:14 UTC, merged