Lookup/dthf UI 4667
po-ui/po-angular pull request #774
Opened 2021-01-21 17:46 UTC by alvarocamillont

**< COMPONENTE >**

**< NÚMERO DA ISSUE >**
_____________________________________________________________________________

**PR Checklist**

- [ ] Código
- [ ] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**

**Qual o novo comportamento?**

**Simulação**

2021-01-28 20:09 UTC, samir-ayoub submitted a review, later dismissed

2021-01-29 13:00 UTC, jhonyeduardo requested changes
Caso alterar o valor do Lookup, via "programação" o formulario não esta ficando pending

https://user-images.githubusercontent.com/6907801/106277167-64cf2900-6217-11eb-9160-aaa4247fa8ec.mp4

2021-01-29 19:01 UTC, jhonyeduardo approved these changes

2021-01-29 19:29 UTC, samir-ayoub approved these changes

2021-01-29 19:29 UTC, merged