feat(chart): permite valores negativos em gráficos do tipo `column`
po-ui/po-angular pull request #802
Opened 2021-02-26 19:52 UTC by samir-ayoub

**po-chart**

**DTHFUI-4737**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [x] Samples

**Qual o comportamento atual?**
Não era possível declarar séries com valores negativos em gráficos do tipo `column`.

**Qual o novo comportamento?**
É possível utilizar séries contendo tanto valores positivos quanto negativos em gráficos dos tipos `collumn` e também em combinações entre `line` e `column`.

**Simulação**
Efetuar testes no sample labs e também verificar o sample de caso de uso.

2021-03-01 14:33 UTC, brunoromeiro approved these changes

2021-03-02 12:39 UTC, brunoromeiro requested changes
Ao inserir série com apenas valores positivos, verificou-se quebra de layout conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/12400333/109649470-b894a100-7b3a-11eb-8592-073a62fac218.png)

2021-03-02 14:36 UTC, brunoromeiro approved these changes

2021-03-02 14:41 UTC, jhonyeduardo approved these changes

2021-03-02 14:42 UTC, merged