fix(table): corrige apresentação do gerenciador de colunas
po-ui/po-angular pull request #854
Opened 2021-04-22 21:04 UTC by alinelariguet

Corrige discrepância entre as colunas visíveis e as informações apresentadas no gerenciador de colunas.

Fixes DTHFUI-4861

**PO-TABLE**

**DTHFUI-4861**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
 Ao repassar novas colunas com definições de visibilidade diferente da atual, não atualiza corretamente o gerenciador de colunas.

**Qual o novo comportamento?**
Corrigida discrepância entre as colunas visíveis e as informações apresentadas no gerenciador de colunas.

**Simulação**
[app-table.zip](https://github.com/po-ui/po-angular/files/6361231/app-table.zip)

2021-04-22 22:20 UTC, brunoromeiro approved these changes

2021-04-22 22:35 UTC, brunoromeiro submitted a review, later dismissed

2021-04-23 17:41 UTC, jhonyeduardo requested changes
- O evento p-change-visible-columns está sendo disparado no resize da pagina, e;
- toda vez que fecho o gerenciador de colunas, mesmo não manipulando.

2021-05-07 19:08 UTC, brunoromeiro approved these changes

2021-05-07 19:26 UTC, jhonyeduardo approved these changes

2021-05-07 19:27 UTC, merged