feat(combo): adiciona condicional para listar os itens do combo
po-ui/po-angular pull request #940
Opened 2021-07-20 20:25 UTC by jcorrea97

PO-COMBO

DTHFUI-2273
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
Ao selecionar um item do combo via click ou teclado(Enter) os outros itens(estáticos ou vindos de um serviço) não aparecerão na listagem. Caso o usuário queira escolher outro item, deve apagar o valor do input para aparecer novamente os outros itens.

**Qual o novo comportamento?**
Ao selecionar um item do combo via click ou teclado(Enter) os outros itens(estáticos ou vindos de um serviço) permanecerão visíveis no combo.

**Simulação**

`index.html`
```
<div class="po-row">
  <po-combo
    class="po-lg-6"
    name="heroName"
    [(ngModel)]="heroName"
    p-field-label="name"
    p-field-value="name"
    p-filter-service="https://po-sample-api.herokuapp.com/v1/heroes"
    p-label="Lista via serviço">
  </po-combo>
  <div class="po-lg-6">
    {{ heroName }}
  </div>
</div>

<div class="po-row">
  <po-combo
    class="po-lg-6"
    name="city"
    [(ngModel)]="city"
    p-label="Lista estatica"
    p-placeholder="Select a location"
    p-required
    p-sort
    [p-options]="citiesOptions">
  </po-combo>
  <div class="po-lg-6">
    {{ city }}
  </div>
</div>

```
`app.component.html`
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {

  city: any;
  heroName: any;

  citiesOptions = [
    { label: 'Allergist', value: 'allergist' },
    { label: 'Cardiologist', value: 'cardiologist' },
    { label: 'General practitioner', value: 'generalPractitioner' },
    { label: 'Dermatologist', value: 'dermatologist' },
    { label: 'Gynecologist', value: 'gynecologist' },
    { label: 'Nutritionist', value: 'nutritionist' },
    { label: 'Pediatrist', value: 'pediatrist' },
    { label: 'Psychiatrist', value: 'psychiatrist' },
    { label: 'Orthopaedist', value: 'orthopaedist' }
  ];

}
```

2021-07-22 14:50 UTC, alinelariguet approved these changes

2021-07-22 14:50 UTC, rafaellmarques submitted a review, later dismissed

2021-07-22 21:00 UTC, jhonyeduardo requested changes
Ao apertar a tecla TAB ou ESC quando não tem serviço, esta mantendo apenas o registro selecionado na lista de opções

2021-07-23 14:30 UTC, rafaellmarques approved these changes

2021-07-23 14:30 UTC, alinelariguet approved these changes

2021-07-23 14:59 UTC, jhonyeduardo approved these changes

2021-07-23 14:59 UTC, jhonyeduardo approved these changes

2021-07-23 14:59 UTC, merged