Sample page login/dthf UI 2668
po-ui/po-angular pull request #949
Opened 2021-07-27 17:55 UTC by jcorrea97

Altera url da Api de autenticação e recuperação de senha no sample de page-login
DTHFUI-2668

Simulação:
https://github.com/po-ui/po-sample-api/pull/21
npm run start:dev

Samples:
PO Page Login - Automatic Service
PO Page Login - Human Resources

2021-07-27 19:04 UTC, jhonyeduardo commented on projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-automatic-service/sample-po-page-login-automatic-service.component.html
> +  p-authentication-url="http://localhost:3000/v1/users/authentication"
alterar para https://po-sample-api.herokuapp.com/v1/users

2021-07-27 19:06 UTC, jhonyeduardo requested changes
1. O tipo de commit deve ser "docs"
ex: docs(page-login): altera url de recuperacao e autenticacao

2. A simulação esta breve, `npm run start:dev` é para rodar o po-sample-api e não o portal

2021-07-28 17:09 UTC, jhonyeduardo commented on projects/templates/src/lib/components/po-page-login/samples/sample-po-page-login-automatic-service/sample-po-page-login-automatic-service.component.html
> +  p-authentication-url="https://localhost:3000/v1/users/authentication"
```suggestion
  p-authentication-url="https://po-sample-api.herokuapp.com/v1/authentication"
```

2021-07-29 18:11 UTC, rafaellmarques approved these changes

2021-07-30 18:51 UTC, jhonyeduardo approved these changes

2021-07-30 18:51 UTC, merged