feat(page-login): retira exibição de icone caso a dica seja vazia
po-ui/po-angular pull request #985
Opened 2021-08-24 18:20 UTC by jcorrea97

**page-login**

**DTHFUI-5136**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [ ] Documentação
- [ ] Samples

**Qual o comportamento atual?**
Ao atribuir valor vazio para as propriedades `loginHint` e `rememberUserHint` o ícone continua aparecendo mesmo sem dica.

**Qual o novo comportamento?**
Ao atribuir valor vazio para as propriedades `loginHint` e `rememberUserHint` o ícone não é exibido

**Simulação**
`app.component.html` :

```
<po-page-login [p-literals]="{loginHint: '', rememberUserHint: ''}">
</po-page-login>
```

2021-08-26 12:57 UTC, brunoromeiro submitted a review, later dismissed

2021-08-26 12:59 UTC, rafaellmarques submitted a review, later dismissed

2021-08-31 18:45 UTC, rafaellmarques submitted a review, later dismissed

2021-09-01 18:04 UTC, jhonyeduardo requested changes
![image](https://user-images.githubusercontent.com/6907801/131721235-e3f7c620-2434-493e-8e78-c79f9be4a1da.png)

2021-09-03 19:04 UTC, brunoromeiro approved these changes

2021-09-03 19:04 UTC, rafaellmarques approved these changes

2021-09-03 19:04 UTC, jribeiroo approved these changes

2021-09-03 21:08 UTC, jhonyeduardo approved these changes

2021-09-03 21:09 UTC, merged