feat(multiselect): permite informar url como string
po-ui/po-angular pull request #995
Opened 2021-09-08 13:21 UTC by jcorrea97

**MultiSelect**

**DTHFUI-5250**
_____________________________________________________________________________

**PR Checklist**

- [x] Código
- [x] Testes unitários
- [x] Documentação
- [x] Samples

**Qual o comportamento atual?**
Não permite passar uma `string` como parâmetro para utilizar um serviço.

**Qual o novo comportamento?**
Permite informar url como `string` para utilizar um serviço no `multiselect`.

**Simulação**
`app.component.html`:

```
<po-multiselect
  class="po-md-6"
  name="multiselect"
  p-label="Search a Hero"
  [(ngModel)]="heroes"
  p-filter-service="https://po-sample-api.herokuapp.com/v1/heroes"
  [p-debounce-time]="debounce"
>
</po-multiselect>
```

`app.component.ts`:

```
import { Component } from '@angular/core';
import { PoMultiselectFilter, PoTableColumn } from '../../../ui/src/lib';
import { TesteHeroesService } from './testehero.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  debounce = 500;
  heroes: Array<string>;
  multiselect: Array<string> = ['1495831666871', '1405833068599'];

  filterService: PoMultiselectFilter;

}
```

2021-09-09 13:23 UTC, brunoromeiro requested changes

2021-09-09 13:23 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
> +import { EventEmitter, Input, OnInit, Output, Directive, OnChanges, SimpleChanges } from '@angular/core';
`OnChanges` e `SimpleChanges` não estão sendo utilizados.

2021-09-09 13:23 UTC, brunoromeiro commented on projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-filter.service.ts
> +      .get(`${this.url}`, {
Poderia ser passado apenas `.get(this.url)` visto que esse cara já é uma string.

2021-09-09 20:14 UTC, brunoromeiro approved these changes

2021-09-09 20:26 UTC, rafaellmarques submitted a review, later dismissed

2021-09-09 21:26 UTC, brunoromeiro submitted a review, later dismissed

2021-09-09 22:04 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
> +   * PoMultiSelectOption.
```suggestion
   * `PoMultiSelectOption`.
```

2021-09-09 22:05 UTC, jhonyeduardo commented on projects/ui/src/lib/components/po-field/po-multiselect/po-multiselect-base.component.ts
> +   * PoMultiSelectOption.
```suggestion
   * `PoMultiSelectOption`.
```

2021-09-09 22:08 UTC, jhonyeduardo requested changes
Ao alterar as proprieades fieldValue, fieldLabel e filterService, o componente não atualiza a lista de opções.

_sugestão: No setService aplicar isFirstFilter=true_

https://user-images.githubusercontent.com/6907801/132768829-f5045d3a-6626-4e28-bdeb-4d6d7b2701f1.mp4

2021-09-09 22:19 UTC, jhonyeduardo requested changes
Adicionar documentação do uso da propriedade filterService quando usada via string/url;

utilizar PoCombo como exemplo: https://po-ui.io/documentation/po-combo

sugestão:
```
Nesta propriedade pode ser informada a URL do serviço em que será realizado o filtro para carregamento da lista de itens no componente.

Também existe a possibilidade de informar um serviço implementando a interface `PoMultiselectFilter`.

Caso utilizado uma URL, o serviço deve ser retornado no padrão [API PO UI](https://po-ui.io/guides/api) e utiliza as propriedades `p-field-label` e `p-field-value` para a construção da lista de itens.

Quando utilizada uma URL de serviço, então será concatenada nesta URL o valor que deseja-se filtrar da seguinte forma:

` ` ` [REMOVER ESPAÇOS]
// caso filtrar por "Peter"
https://localhost:8080/api/heroes?filter=Peter
` ` `

E caso iniciar o campo com valor, os itens serão buscados da seguinte forma:

` ` ` [REMOVER ESPAÇOS]
// caso o valor do campo for [1234, 5678];

https://localhost:8080/api/heroes?value=1234,5678
` ` `

O *value* é referente ao `fieldValue`.

```

2021-09-10 19:03 UTC, brunoromeiro approved these changes

2021-09-10 19:10 UTC, rafaellmarques approved these changes

2021-09-10 19:24 UTC, jhonyeduardo approved these changes

2021-09-10 19:24 UTC, merged